[package]
name = "chitauri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
clap = { version = "3", features = ["derive"] }
rust-s3 = "0.29"
serde = { version = "1", features = ["derive"] }
serde_bencode = "0.2"
serde_bytes = "0.11"
serde_yaml = "0.8"
thiserror = "1"
url = "2"