name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0

    - name: Set up Go
      uses: actions/setup-go@v2.1.3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
